---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: efs-manager
  name: efs-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      component: efs-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: efs-manager
    spec:
      containers:
      - name: efs-manager
        image: docker-registry.default.svc:5000/openshift-efs-stunnel/efs-manager:latest
        imagePullPolicy: Always
        #livenessProbe:
        #readinessProbe:
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        node-role.kubernetes.io/infra: "true"
      restartPolicy: Always
      securityContext: {}
      serviceAccount: efs-manager
      serviceAccountName: efs-manager
      terminationGracePeriodSeconds: 30
