---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: RHEL7
  name: rhel7
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: RHEL 7 base image
      openshift.io/display-name: RHEL 7
      openshift.io/provider-display-name: Red Hat, Inc.
    from:
      kind: DockerImage
      name: registry.redhat.io/rhel7:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local

