---
apiVersion: v1
kind: Pod
metadata:
  labels:
    deployment: docker-registry-1
    deploymentconfig: docker-registry
    docker-registry: default
  name: efs-stunnel-test
spec:
  containers:
  - name: test
    command:
    - /bin/sh
    - -c
    - while true; do sleep 1000; done
    image: 172.30.1.1:5000/openshift/rhel7:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    volumeMounts:
    - mountPath: /efs-stunnel-test
      name: efs-stunnel-test
  volumes:
  - name: efs-stunnel-test
    persistentVolumeClaim:
      claimName: efs-stunnel-test
